"use strict";
exports.__esModule = true;
var mobile_1 = require("./mobile");
var nokia3210 = new mobile_1.Mobile("nokia", "3210", "nokia", "512GB", "azul", false, 1, 90);
var iphone3G = new mobile_1.Mobile("Iphone", "8", "apple", "256GB", "Blanco", true, 3, 400);
var samsungGalaxy10 = new mobile_1.Mobile("Samsung", "Galaxy10", "Samsung", "128GB", "rosa", true, 2, 190);
console.log("NOKIA 3210");
console.log(nokia3210);
console.log("IPHONE3G");
console.log(iphone3G);
console.log("SAMSUNG GALAXY10");
console.log(samsungGalaxy10);
// console.log("NOKIA CON LOS CAMBIOS");
// nokia3210.cameraNumber = 4;
// nokia3210.is5G = true
// console.log(nokia3210);
console.log("The characteristics of the Nokia are");
console.log(nokia3210.toString());
console.log("The characteristics of the Iphone are");
console.log(iphone3G.toString());
console.log("The characteristics of the Samsung are");
console.log(samsungGalaxy10.toString());
